//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST10084795_POE_Part2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public string StartDate { get; set; }
        public int TotalWeeks { get; set; }
        public string ModuleCode { get; set; }
        public string ModuleName { get; set; }
        public int Credits { get; set; }
        public int ClassHours { get; set; }
        public int RequiredStudyHrs { get; set; }
    }
}
