//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST10084795_POE_Part2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelfStudy
    {
        public int ID { get; set; }
        public string ModuleCode { get; set; }
        public int Week { get; set; }
        public string StudyDate { get; set; }
        public int FinishedStudyHrs { get; set; }
        public int RemainingStudyHrs { get; set; }
    }
}
